version: '3.7'

services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://localhost:27017
    depends_on:
      - mongo

volumes:
  data: