name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.0.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t sulcer/bicycle-sharing-payment-service  -f src/main/docker/Dockerfile.jvm .

      - name: Push Docker image
        run: docker push sulcer/bicycle-sharing-payment-service